

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 357)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 551, 341))
        self.stackedWidget.setObjectName("stackedWidget")
        self.newCollection = QtWidgets.QWidget()
        self.newCollection.setObjectName("newCollection")
        self.nextpage2 = QtWidgets.QPushButton(self.newCollection)
        self.nextpage2.setGeometry(QtCore.QRect(410, 280, 131, 41))
        self.nextpage2.setObjectName("nextpage2")
        self.collectionNameLine = QtWidgets.QLineEdit(self.newCollection)
        self.collectionNameLine.setGeometry(QtCore.QRect(160, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.collectionNameLine.setFont(font)
        self.collectionNameLine.setText("")
        self.collectionNameLine.setObjectName("collectionNameLine")
        self.collectionNameLabel = QtWidgets.QLabel(self.newCollection)
        self.collectionNameLabel.setGeometry(QtCore.QRect(100, 110, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.collectionNameLabel.setFont(font)
        self.collectionNameLabel.setObjectName("collectionNameLabel")
        self.stackedWidget.addWidget(self.newCollection)
        self.newListPage = QtWidgets.QWidget()
        self.newListPage.setObjectName("newListPage")
        self.nextpage3 = QtWidgets.QPushButton(self.newListPage)
        self.nextpage3.setGeometry(QtCore.QRect(390, 280, 131, 41))
        self.nextpage3.setObjectName("nextpage3")
        self.listlabel = QtWidgets.QLabel(self.newListPage)
        self.listlabel.setGeometry(QtCore.QRect(30, 40, 221, 16))
        self.listlabel.setObjectName("listlabel")
        self.search = QtWidgets.QLineEdit(self.newListPage)
        self.search.setGeometry(QtCore.QRect(20, 230, 501, 21))
        self.search.setObjectName("search")
        self.backpage3 = QtWidgets.QPushButton(self.newListPage)
        self.backpage3.setGeometry(QtCore.QRect(20, 280, 131, 41))
        self.backpage3.setObjectName("backpage3")
        self.listWidget = QtWidgets.QListWidget(self.newListPage)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 501, 161))
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.stackedWidget.addWidget(self.newListPage)
        self.attrListPage = QtWidgets.QWidget()
        self.attrListPage.setObjectName("attrListPage")
        self.attrSearch = QtWidgets.QLineEdit(self.attrListPage)
        self.attrSearch.setGeometry(QtCore.QRect(20, 230, 501, 21))
        self.attrSearch.setObjectName("attrSearch")
        self.backpage4 = QtWidgets.QPushButton(self.attrListPage)
        self.backpage4.setGeometry(QtCore.QRect(20, 290, 131, 41))
        self.backpage4.setObjectName("backpage4")
        self.nextpage4 = QtWidgets.QPushButton(self.attrListPage)
        self.nextpage4.setGeometry(QtCore.QRect(390, 290, 131, 41))
        self.nextpage4.setObjectName("nextpage4")
        self.listlabel_2 = QtWidgets.QLabel(self.attrListPage)
        self.listlabel_2.setGeometry(QtCore.QRect(30, 40, 221, 16))
        self.listlabel_2.setObjectName("listlabel_2")
        self.attrListCollection = QtWidgets.QListWidget(self.attrListPage)
        self.attrListCollection.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.attrListCollection.setGeometry(QtCore.QRect(20, 60, 501, 161))
        self.attrListCollection.setObjectName("attrList")
        self.stackedWidget.addWidget(self.attrListPage)
        self.shaderPage = QtWidgets.QWidget()
        self.shaderPage.setObjectName("shaderPage")
        self.finishBtn = QtWidgets.QPushButton(self.shaderPage)
        self.finishBtn.setGeometry(QtCore.QRect(390, 290, 131, 41))
        self.finishBtn.setObjectName("finishBtn")
        self.shaderLabel = QtWidgets.QLabel(self.shaderPage)
        self.shaderLabel.setGeometry(QtCore.QRect(20, 30, 221, 16))
        self.shaderLabel.setObjectName("shaderLabel")
        self.shaderListCollection = QtWidgets.QListWidget(self.shaderPage)
        self.shaderListCollection.setGeometry(QtCore.QRect(20, 50, 501, 161))
        self.shaderListCollection.setObjectName("collectionShaderList")
        self.shaderSearch = QtWidgets.QLineEdit(self.shaderPage)
        self.shaderSearch.setGeometry(QtCore.QRect(20, 250, 501, 21))
        self.shaderSearch.setObjectName("shaderSearch")
        self.backpage5 = QtWidgets.QPushButton(self.shaderPage)
        self.backpage5.setGeometry(QtCore.QRect(20, 290, 131, 41))
        self.backpage5.setObjectName("backpage5")
        self.nameShaderCollection = QtWidgets.QLineEdit(self.shaderPage)
        self.nameShaderCollection.setGeometry(QtCore.QRect(20, 220, 501, 21))
        self.nameShaderCollection.setObjectName("collectionNameShader")
        self.stackedWidget.addWidget(self.shaderPage)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nextpage2.setText(_translate("Form", "Next"))
        self.collectionNameLine.setPlaceholderText(_translate("Form", "Enter name of collection"))
        self.collectionNameLabel.setText(_translate("Form", "Enter name of the Collection"))
      
        self.nextpage3.setText(_translate("Form", "Next"))
        self.listlabel.setText(_translate("Form", "Select the objects for the collection from list :"))
        self.search.setPlaceholderText(_translate("Form", "Search the List"))
        self.backpage3.setText(_translate("Form", "Back"))
        self.attrSearch.setPlaceholderText(_translate("Form", "Search the List"))
        self.backpage4.setText(_translate("Form", "Back"))
        self.nextpage4.setText(_translate("Form", "Next"))
        self.listlabel_2.setText(_translate("Form", "Select the attributes you want to overide "))
        self.finishBtn.setText(_translate("Form", "Finish"))
        self.shaderLabel.setText(_translate("Form", "Select the shaders you want to overide "))
        self.shaderSearch.setPlaceholderText(_translate("Form", "Search the List"))
        self.backpage5.setText(_translate("Form", "Back"))
        self.nameShaderCollection.setPlaceholderText(_translate("Form", "Name the shader"))
